// svelte/src/routes/components/+page.svelte
<script>
	// @ts-nocheck

	// @ts-ignore
	import { Login } from '@boxyhq/svelte-ui/sso';
	import Navbar from '../Navbar.svelte';
	import Prism from 'prismjs';

	let customStylesCode = `<script>\n  import { Login } from '@boxyhq/svelte-ui';\n  import demo1 from './demo1.css?inline'\n\n  async function onSubmitButton() {\n     // initiate the SSO flow here\n  };\n< /script>\n\n<main>\n  <Login\n    onSubmit={onSubmitButton}\n    styles={{\n      input: { borderColor: '#ebedf0' },\n      button: { padding: '.85rem' },\n    }}\n    classNames={{ button: 'btn', input: 'inp' }}\n    placeholder='contoso@boxyhq.com'\n    inputLabel='Team Domain *'\n    buttonText='Login with SSO'\n    innerProps={{ input: { type: 'email' } }}\n  />;\n</main>`;
	let defaultStylesCode = `<script>\n  import { Login } from '@boxyhq/svelte-ui';\n\n  async function onSubmitButton() {\n     // initiate the SSO flow here\n  };\n< /script>\n\n<main>\n  <Login\n    onSubmit={onSubmitButton}\n    styles={{ input: { border: '1px solid darkcyan' } }}\n    placeholder='contoso@boxyhq.com'\n    inputLabel='Team Domain *'\n  />;\n</main>`;
	let loginWithoutInputCode = `<script>\n  import { Login } from '@boxyhq/svelte-ui';\n\n  async function onSubmitButton() {\n     // initiate the SSO flow here\n  };\n< /script>\n\n<main>\n  <Login\n    onSubmit={onSubmitButton}\n    ssoIdentifier={'some-identifier'}\n    buttonText='SIGN IN WITH SSO'\n  />;\n</main>`;
	let loginWithFailingOnsubmitCode = `<script>\n  import { Login } from '@boxyhq/svelte-ui';\n\n  async onSubmitButton() => ({\n     error: {\n      message: 'Invalid team domain',\n     },\n  });\n< /script>\n\n<main>\n  <Login\n    onSubmit={onSubmitButton}\n    inputLabel='Team Domain *'\n    placeholder='contoso@boxyhq.com'\n  />;\n</main>`;

	let language = 'javascript';
	let customStylesIsActive = false;
	let defaultStylesIsActive = false;
	let withoutInputIsActive = false;
	let withFailingOnsubmitIsActive = false;

	// @ts-ignore
	async function onSubmitButtonFail({ ssoIdentifier, cb }) {
		cb({
			error: {
				message: 'Invalid team domain'
			}
		});
	}

	// @ts-ignore
	async function onSubmitButton({ cb }) {
		console.log('SSO flow initiated');

		// cb({
		// 	error: {
		// 		message: ''
		// 	}
		// });
	}
</script>

<main>
	<Navbar />
	<div class="hero-body">
		<div class="login-with-custom-styles">
			<Login
				styles={{
					input: { borderColor: '#ebedf0' },
					button: { padding: '.85rem' }
				}}
				classNames={{ button: 'btn', input: 'inp' }}
				onSubmit={onSubmitButton}
				placeholder={'contoso@boxyhq.com'}
				inputLabel={'Team Domain *'}
				buttonText={'Login with SSO'}
				innerProps={{ input: { id: 'demo1' }, label: { for: 'demo1' } }}
			/>
			<h2 class="custom-styles-title">Login with custom styling</h2>
			<h2 class="custom-styles-description">
				Refer the code below to see the passed props. Also supported is the passing of style
				attribute for each inner element (Note that inline style will override other styles).
			</h2>
			<button class="btn-toggle" on:click={() => (customStylesIsActive = !customStylesIsActive)}
				>Hide code</button
			>
			<div class="code-to-be-highlighted" class:active={customStylesIsActive}>
				<code>
					{@html Prism.highlight(customStylesCode, Prism.languages[language])}
				</code>
			</div>
		</div>
		<div class="login-with-default-styles">
			<Login
				onSubmit={onSubmitButton}
				inputLabel={'Team domain*'}
				buttonText={'Login with SSO'}
				styles={{ input: { border: '1px solid darkcyan' } }}
				placeholder={'contos@boxyhq.com'}
			/>
			<h2 class="default-styles-title">Login Component with default styles</h2>
			<h2 class="default-styles-description">
				If classNames prop is not passed in, then default styling will be applied. Also supported is
				the passing of style attribute for each inner element (Note that inline style will override
				other styles).
			</h2>
			<button class="btn-toggle" on:click={() => (defaultStylesIsActive = !defaultStylesIsActive)}
				>Hide code</button
			>
			<div class="code-to-be-highlighted" class:active={defaultStylesIsActive}>
				<code>
					{@html Prism.highlight(defaultStylesCode, Prism.languages[language])}
				</code>
			</div>
		</div>
		<div class="login-without-input">
			<Login
				onSubmit={onSubmitButton}
				ssoIdentifier={'some-identifier'}
				buttonText={'SIGN IN WITH SSO'}
			/>
			<h2 class="login-without-input-title">Login Component without input display</h2>
			<h2 class="login-without-input-title-description">
				Here we pass the ssoIdentifier directly instead of taking a user input.
			</h2>
			<button class="btn-toggle" on:click={() => (withoutInputIsActive = !withoutInputIsActive)}
				>Hide code</button
			>
			<div class="code-to-be-highlighted" class:active={withoutInputIsActive}>
				<code>
					{@html Prism.highlight(loginWithoutInputCode, Prism.languages[language])}
				</code>
			</div>
		</div>
		<div class="login-with-failing-onsubmit">
			<Login
				inputLabel={'Team domain*'}
				placeholder={'contos@boxyhq.com'}
				onSubmit={onSubmitButtonFail}
			/>
			<h2 class="login-with-failing-onsubmit-title">Login Component with failing onSubmit</h2>
			<h2 class="login-with-failing-onsubmit-description">
				If error object is returned with the error message, the message would be displayed inline.
			</h2>
			<button
				class="btn-toggle"
				on:click={() => (withFailingOnsubmitIsActive = !withFailingOnsubmitIsActive)}
				>Hide code</button
			>
			<div class="code-to-be-highlighted" class:active={withFailingOnsubmitIsActive}>
				<code>
					{@html Prism.highlight(loginWithFailingOnsubmitCode, Prism.languages[language])}
				</code>
			</div>
		</div>
	</div>
</main>

<svelte:head>
	<link
		href="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/themes/prism.min.css"
		rel="stylesheet"
	/>
</svelte:head>

<style global>
	/* .code {
    white-space: pre-wrap;
  } */

	.active {
		display: none;
	}

	.hero-body {
		padding: 0 40px;
		color: #24292e;
		font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu,
			Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
	}

	.login-with-custom-styles,
	.login-with-default-styles,
	.login-without-input,
	.login-with-failing-onsubmit {
		border: 1px solid rgba(5, 5, 5, 0.1);
		padding: 20px;
		margin: 15px 0;
	}

	.login-with-custom-styles h2,
	.login-with-default-styles h2,
	.login-without-input h2,
	.login-with-failing-onsubmit h2 {
		font-size: 16px;
		font-weight: normal;
	}

	.custom-styles-title,
	.default-styles-title,
	.login-without-input-title,
	.login-with-failing-onsubmit-title {
		margin: 10px 0;
		padding-bottom: 0.3em;
		border-bottom: 1px solid #eaecef;
	}

	.custom-styles-description,
	.default-styles-description,
	.login-without-input-title-description,
	.login-with-failing-onsubmit-description {
		padding-bottom: 0.4em;
		border-bottom: 1px dashed #eaecef;
	}

	.code-to-be-highlighted {
		white-space: pre-wrap;
		color: rgb(57, 58, 52);
		background-color: rgb(246, 248, 250);
		padding: 16px;
		overflow: auto;
		line-height: 1.45;
		background-color: #f6f8fa;
		border-radius: 3px;
	}

	.btn-toggle {
		cursor: pointer;
		margin: 0 0 1em 0;
		background: #0070f3;
		color: #fff;
		padding: 0.5rem 0.7rem;
		border-radius: 5px;
		border: 1px solid #0070f3;
		font-weight: 500;
		font-size: 1rem;
	}

	:global(.btn) {
		background: #0070f3;
		color: #fff;
		padding: 0.5rem 1rem;
		cursor: pointer;
		border-radius: 5px;
		border: 1px solid #0070f3;
		font-weight: 500;
		font-size: 1rem;
		transition: box-shadow 0.15s ease;
	}

	:global(.btn:focus-visible) {
		box-shadow: 0 0 0 1px #fff, 0 0 0 3px #0070f3;
	}

	:global(.btn:disabled) {
		opacity: 0.6;
		pointer-events: none;
	}

	:global(.inp) {
		border-radius: 5px;
		appearance: none;
		height: 40px;
		padding: 0 12px;
		border: 1px solid #f5f5f5;
		margin-bottom: 1rem;
		outline: none;
	}

	:global(.inp:focus) {
		border-color: #666;
	}
</style>

// angular/projects/docs/src/app/components/components.component.ts
import { Component } from '@angular/core';
import { Login } from '@boxyhq/angular-ui/sso';
import { CommonModule } from '@angular/common';
import { NavbarComponent } from '../navbar/navbar.component';
import { PrismService } from '../services/prism.services';
import * as Prism from 'prismjs';

@Component({
  selector: 'app-components',
  template: `
    <app-navbar></app-navbar>
    <div class="border-[rgba(5, 5, 5, 0.1)] border-[1px] p-10 mx-10 my-5">
      <login
        [styles]="customStyles"
        [classNames]="customStyleClasses"
        [inputLabel]="'Team domain*'"
        [placeholder]="'contoso@boxyhq.com'"
        [buttonText]="'Login with SSO'"></login>
      <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">Login with custom styling</h1>
      <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
        Refer the code below to see the passed props. Also supported is the passing of style attribute for
        each inner element (Note that inline style will override other styles).
      </h1>
      <button
        (click)="toggleButton(displayCustomStyle, 'displayCustomStyle')"
        class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
        Hide code
      </button>
      <div *ngIf="displayCustomStyle">
        <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{customStylingCode}}
          </code>
        </pre>
      </div>
    </div>

    <div class="border-[rgba(5, 5, 5, 0.1)] my-5 border-[1px] p-10 mx-10">
      <login
        [styles]="defaultStyles"
        [inputLabel]="'Team domain*'"
        [placeholder]="'contoso@boxyhq.com'"
        [buttonText]="'Login with SSO'"></login>
      <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">
        Login Component with default styles
      </h1>
      <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
        If classNames prop is not passed in, then default styling will be applied. Also supported is the
        passing of style attribute for each inner element (Note that inline style will override other styles).
      </h1>
      <button
        (click)="toggleButton(displayDefaultStyle, 'displayDefaultStyle')"
        class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
        Hide code
      </button>
      <div *ngIf="displayDefaultStyle">
        <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{defaultStylesCode}}
          </code>
        </pre>
      </div>
    </div>

    <div class="border-[rgba(5, 5, 5, 0.1)] my-5 border-[1px] p-10 mx-10">
      <login
        [ssoIdentifier]="'some-sso-identifier'"
        [buttonText]="'SIGN IN WITH SSO'"
        (onSubmit)="onSubmitFailing($event)"></login>
      <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">
        Login Component without input display
      </h1>
      <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
        Here we pass the ssoIdentifier directly instead of taking a user input.
      </h1>
      <button
        (click)="toggleButton(displayLoginWithouInput, 'displayLoginWithouInput')"
        class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
        Hide code
      </button>
      <div *ngIf="displayLoginWithouInput">
        <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{loginWithoutInputCode}}
          </code>
        </pre>
      </div>
    </div>

    <div class="border-[rgba(5, 5, 5, 0.1)] my-5 border-[1px] p-10 mx-10">
      <login
        [inputLabel]="'Team domain*'"
        (onSubmit)="onSubmitFailing($event)"
        [styles]="onsubmitFailStyles"
        [placeholder]="'contoso@boxyhq.com'"
        [buttonText]="'SIGN IN WITH SSO'"></login>
      <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">
        Login Component with failing onSubmit
      </h1>
      <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
        If error object is returned with the error message, the message would be displayed inline.
      </h1>
      <button
        (click)="toggleButton(displayFailingOnSubmit, 'displayFailingOnSubmit')"
        class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
        Hide code
      </button>
      <div *ngIf="displayFailingOnSubmit">
        <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{failingOnSubmitCode}}
          </code>
        </pre>
      </div>
    </div>
  `,
  standalone: true,
  imports: [CommonModule, NavbarComponent, Login],
  styleUrls: ['./components.component.css'],
})
export class ComponentsComponent {
  displayCustomStyle = true;
  displayDefaultStyle = true;
  displayLoginWithouInput = true;
  displayFailingOnSubmit = true;

  customStyleClasses = {
    button: 'btn',
    input: 'inp',
  };

  defaultStyles = {
    container: {
      display: 'flex',
      'flex-direction': 'column',
      width: '50%',
    },
    input: { border: '1px solid darkcyan' },
  };

  customStyles = {
    container: {
      display: 'flex',
      'flex-direction': 'column',
      width: '50%',
    },
    input: {
      'border-color': '#ebedf0',
    },
    button: {
      padding: '.85rem',
      marginLeft: '0',
    },
  };

  onsubmitFailStyles = {
    container: {
      display: 'flex',
      'flex-direction': 'column',
      width: '50%',
    },
  };

  onSubmitFailing = async function ({
    ssoIdentifier,
    cb,
  }: {
    ssoIdentifier: string;
    cb: (err: { error: { message: string } } | null) => void;
  }) {
    console.log('SSO flow initiated');
    console.log(ssoIdentifier);

    cb({
      error: {
        message: 'Invalid team domain',
      },
    });
  };

  toggleButton(propValue: boolean, propName: string) {
    if (propName === 'displayCustomStyle') {
      this.displayCustomStyle = !propValue;
    } else if (propName === 'displayDefaultStyle') {
      this.displayDefaultStyle = !propValue;
    } else if (propName === 'displayLoginWithouInput') {
      this.displayLoginWithouInput = !propValue;
    } else if (propName === 'displayFailingOnSubmit') {
      this.displayFailingOnSubmit = !propValue;
    } else {
      return;
    }
  }

  customStylingCode = `  import { Component } from '@angular/core';
  import { CommonModule } from '@angular/common';
  import { LoginTrialComponent } from '@boxyhq/angular-ui';
    
    @Component({
      selector: "my-component, MyComponent",
      template: '
      <sso-login
        [classNames]="componentClassnames"
        [styles]="componentStyles"
        [buttonText]="'Login with SSO'"
        [inputLabel]="'Team Domain*'"
        [placeholder]="'contoso@boxyhq.com'"
        (onSubmit)="onSubmitButton($event)"></sso-login>
      ',
      standalone: true,
      imports: [CommonModule, LoginComponent],
      styleUrls: ['./my-component.component.css'],
    })
    export class MyComponent{
      componentStyles = {
        input: { borderColor: '#ebedf0' },
        button: { padding: '.85rem' }
      }
  
      componentClassnames = {
        button:'btn',
        input: 'inp'
      };
    
      async function onSubmitButton() {
        // initiate the SSO flow here
     };
    }`;

  defaultStylesCode = `    import { Component } from '@angular/core';
    import { CommonModule } from '@angular/common';
    import { LoginTrialComponent } from '@boxyhq/angular-ui';
        
      @Component({
        selector: "my-component, MyComponent",
        template: '
        <sso-login
          [styles]="componentStyles"
          [inputLabel]="'Team Domain*'"
          [placeholder]="'contoso@boxyhq.com'"
          (onSubmit)="onSubmitButton($event)"></sso-login>
        ',
        standalone: true,
        imports: [CommonModule, LoginComponent],
        styleUrls: ['./my-component.component.css'],
      })
      export class MyComponent{
        componentStyles = {
          input: { border: '1px solid darkcyan' },
        }
    
        async function onSubmitButton() {
          // initiate the SSO flow here
        };
      }`;

  loginWithoutInputCode = `    import { Component } from '@angular/core';
    import { CommonModule } from '@angular/common';
    import { LoginTrialComponent } from '@boxyhq/angular-ui';
          
      @Component({
        selector: "my-component, MyComponent",
        template: '
          <sso-login
              [buttonText]="'SIGN IN WITH SSO'"
              [ssoIdentifier]="'some-identifier'"
              (onSubmit)="onSubmitButton($event)"></sso-login>
          ',
        standalone: true,
        imports: [CommonModule, LoginComponent],
        styleUrls: ['./my-component.component.css'],
      })
      export class MyComponent{
        async function onSubmitButton() {
          // initiate the SSO flow here
        };
      }`;

  failingOnSubmitCode = `    import { Component } from '@angular/core';
    import { CommonModule } from '@angular/common';
    import { LoginTrialComponent } from '@boxyhq/angular-ui';
                
      @Component({
        selector: "my-component, MyComponent",
        template: '
            <sso-login
              [buttonText]="'SIGN IN WITH SSO'"
              [ssoIdentifier]="'some-identifier'"
              (onSubmit)="onSubmitFailing($event)"></sso-login>
            ',
        standalone: true,
        imports: [CommonModule, LoginComponent],
        styleUrls: ['./my-component.component.css'],
      })
      export class MyComponent{
        async function onSubmitButton() {
          // initiate the SSO flow here
        };
      }`;

  codeType = 'javascript';
  highlighted = false;

  constructor(private prismService: PrismService) {}

  ngAfterContentChecked() {
    Prism.highlightAll();
  }

  ngAfterViewChecked() {
    Prism.highlightAll();
  }

  ngOnDestroy() {
    Prism.highlightAll();
  }
}
