// vue/docs/components/sso/FailingSubmit.vue
<script setup>
import { Login } from '@boxyhq/vue-ui/sso';

async function onSubmit({ ssoIdentifier, cb }) {
  console.log(ssoIdentifier);
  cb({
    error: {
      message: 'Invalid team domain',
    },
  });
}
</script>

<template>
  <Login
    :onSubmit="onSubmit"
    inputLabel="Team domain *"
    placeholder="contoso@boxyhq.com"
    :innerProps="{ input: { id: 'demo4-input' }, label: { for: 'demo4-input' } }" />
</template>

// react/docs/components/sso/FailingSubmit.tsx
/**
 * @title Login Component with failing onSubmit
 * @description If error object is returned with the error message, the message would be displayed inline.
 * @order 4
 */

import { Login } from '@boxyhq/react-ui/sso';

const FailingSubmit = () => {
  return (
    <Login
      onSubmit={async ({ ssoIdentifier, cb }) => {
        console.log(ssoIdentifier);
        cb({
          error: {
            message: 'Invalid team domain',
          },
        });
      }}
      inputLabel='Team domain *'
      placeholder='contoso@boxyhq.com'
    />
  );
};

export default FailingSubmit;
