// react/docs/components/sso/PresetSSOIdentifier.tsx
/**
 * @title Login Component without input display
 * @description Here we pass the ssoIdentifier directly instead of taking a user input.
 * @order 3
 */

import { Login } from '@boxyhq/react-ui/sso';

const PresetSSOIdentifier = () => {
  return (
    <Login
      onSubmit={async ({ ssoIdentifier, cb }) => {
        // initiate the SSO flow here
      }}
      ssoIdentifier='some-identifier'
      buttonText='SIGN IN WITH SSO'
    />
  );
};

export default PresetSSOIdentifier;

// vue/docs/components/sso/PresetSSOIdentifier.vue
<script setup>
import { Login } from '@boxyhq/vue-ui/sso';

function onSubmit({ ssoIdentifier, cb }) {
  // initiate the SSO flow here
  console.log(ssoIdentifier);
}
</script>

<template>
  <Login
    :onSubmit="onSubmit"
    ssoIdentifier="some-identifier"
    buttonText="SIGN IN WITH SSO"
    :innerProps="{ input: { id: 'demo3-input' }, label: { for: 'demo3-input' } }" />
</template>
