// vue/docs/components/demo/demo3.vue
<script setup>
import { Login } from '@boxyhq/vue-ui/sso'

function onSubmit(ssoIdentifier,cb) {
    // initiate the SSO flow here
    console.log(ssoIdentifier)
}
</script>

<template>
     <Login
      :onSubmit={onSubmit}
      ssoIdentifier='some-identifier'
      buttonText='SIGN IN WITH SSO'
    />
</template>

// react/docs/sso/demos/demo3.tsx
/**
 * @title Login Component without input display
 * @description Here we pass the ssoIdentifier directly instead of taking a user input.
 * @order 3
 */

import { Login } from '@boxyhq/react-ui/sso';

const Demo3 = () => {
  return (
    <Login
      onSubmit={async (ssoIdentifier) => {
        // initiate the SSO flow here
      }}
      ssoIdentifier='some-identifier'
      buttonText='SIGN IN WITH SSO'
    />
  );
};

export default Demo3;
