// vue/docs/components/sso/demo1.vue
<script setup>
import { Login } from '@boxyhq/vue-ui/sso';
import './demo1.css';
function onSubmit({ ssoIdentifier, cb }) {
  // initiate the SSO flow here
  console.log(ssoIdentifier);
}
</script>
<template>
  <Login
    :onSubmit="onSubmit"
    :styles="{
      input: { borderColor: '#ebedf0' },
      button: { padding: '.85rem' },
    }"
    :classNames="{ button: 'btn', input: 'inp' }"
    placeholder="contoso@boxyhq.com"
    inputLabel="Team Domain *"
    buttonText="Login with SSO"
    :innerProps="{ input: { type: 'email' } }" />
</template>

// react/docs/sso/demos/demo1.tsx
/**
 * @title Login Component with custom styling
 * @description Refer the code below to see the passed props. Also supported is the passing of style attribute for each inner element (Note that inline style will override other styles).
 * @order 1
 */

import { sso } from '@boxyhq/react-ui';
import './demo1.css';

const { Login } = sso;

const Demo1 = () => {
  return (
    <Login
      onSubmit={async (ssoIdentifier) => {
        // initiate the SSO flow here
      }}
      styles={{
        input: { borderColor: '#ebedf0' },
        button: { padding: '.85rem' },
      }}
      classNames={{ button: 'btn', input: 'inp' }}
      placeholder='contoso@boxyhq.com'
      inputLabel='Team Domain *'
      buttonText='Login with SSO'
      innerProps={{ input: { type: 'email' } }}
    />
  );
};

export default Demo1;
