// vue/docs/components/demo/demo1.vue
<script setup>
import { Login } from '@boxyhq/vue-ui/sso'

function onSubmit(ssoIdentifier,cb) {
    // initiate the SSO flow here
    console.log(ssoIdentifier)
}
</script>
<style>
.btn {
  background: #0070f3;
  color: #fff;
  padding: 0.5rem 1rem;
  cursor: pointer;
  border-radius: 5px;
  border: 1px solid #0070f3;
  font-weight: 500;
  font-size: 1rem;
  transition: box-shadow 0.15s ease;
}

.btn:focus-visible {
  box-shadow: 0 0 0 1px #fff, 0 0 0 3px #0070f3;
}

.btn:disabled {
  opacity: 0.6;
  pointer-events: none;
}

.inp {
  border-radius: 5px;
  appearance: none;
  height: 40px;
  padding: 0 12px;
  border: 1px solid #f5f5f5;
  margin-bottom: 1rem;
  outline: none;
}

.inp:focus {
  border-color: #666;
}

</style>
<template>
    <Login :onSubmit="onSubmit"
      :styles="{
        input: { borderColor: '#ebedf0' },
        button: { padding: '.85rem' },
      }"
      :classNames="{ button: 'btn', input: 'inp' }"
      placeholder='contoso@boxyhq.com'
      inputLabel='Team Domain *'
      buttonText='Login with SSO'
      :innerProps="{ input: { type: 'email' } }"/>
</template>

// react/docs/sso/demos/demo1.tsx
/**
 * @title Login Component with custom styling
 * @description Refer the code below to see the passed props. Also supported is the passing of style attribute for each inner element (Note that inline style will override other styles).
 * @order 1
 */

import { sso } from '@boxyhq/react-ui';
import './demo1.css';

const { Login } = sso;

const Demo1 = () => {
  return (
    <Login
      onSubmit={async (ssoIdentifier) => {
        // initiate the SSO flow here
      }}
      styles={{
        input: { borderColor: '#ebedf0' },
        button: { padding: '.85rem' },
      }}
      classNames={{ button: 'btn', input: 'inp' }}
      placeholder='contoso@boxyhq.com'
      inputLabel='Team Domain *'
      buttonText='Login with SSO'
      innerProps={{ input: { type: 'email' } }}
    />
  );
};

export default Demo1;
